name: spirit
description: Spirit App
version: 1.1.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.15.8
  flutter_launcher_icons: ^0.7.2+1
  http: ^0.12.0+2
  path_provider: ^1.2.0
  optional: ^3.0.2+1
  webview_flutter: ^0.3.10+4
  flutter_local_notifications: ^0.8.0
  url_launcher: ^5.1.1
  dcache: ^0.3.0
  immortal: ^1.1.0
  cached_network_image: ^1.1.1
  package_info: ^0.4.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - assets/initial_schedule.json
     - assets/bands.json
     - assets/logo.png
     - assets/icon_menu.png

  fonts:
    - family: No Continue
      fonts:
        - asset: assets/no_continue.ttf

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon_adaptive.png"
